import { Routes, Route } from 'react-router-dom'
import Batch from './pages/Batch.js'
import BatchForm from './pages/BatchForm.js'
import Navbar from './components/Navbar.js'
import UpdateBatch from './components/UpdateBatch.js'
